# Test request to project creation
POST http://localhost:8080/api/project
Content-Type: application/json

{
    "projectName": "projectName",
	"projectIdentifier": "projectIdentifier2" ,
	"description": "description"
}

###
GET http://localhost:8080/api/project/PROJECTIDENTIFIER2

###


